### ISSUE TITLE
Readme: postgres + rest

### ISSUE THREAD

**Issue by cxkoda** [nicolasbonnici/cryptobot#12]
Hi nicolas,

nice work so far. Could you perhaps add a short quick-start guide in the readme on how you setup the rest + postgres?

Best.

**Comment by nicolasbonnici** [comment]
This is optional, but if you want to build a REST API that script can consume, use your favorite language and database system, or directly persist onto database. In fact i was mostly benchmarking while working on this script and built an API very quickly using PHP 8 with Symfony and API Platform, then i tried to do some import or backtesting directly API side and just was surprised by the huge performance gap with PHP. So ended with no python in my stack, this project is totally different from a bot but it's also about cryptocurrencies and need good performance.
